// Generated by gencpp from file remote/basicResponse.msg
// DO NOT EDIT!


#ifndef REMOTE_MESSAGE_BASICRESPONSE_H
#define REMOTE_MESSAGE_BASICRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace remote
{
template <class ContainerAllocator>
struct basicResponse_
{
  typedef basicResponse_<ContainerAllocator> Type;

  basicResponse_()
    : fb_x(0)
    , fd_y(0)
    , fd_z(0)  {
    }
  basicResponse_(const ContainerAllocator& _alloc)
    : fb_x(0)
    , fd_y(0)
    , fd_z(0)  {
    }



   typedef int32_t _fb_x_type;
  _fb_x_type fb_x;

   typedef int32_t _fd_y_type;
  _fd_y_type fd_y;

   typedef int32_t _fd_z_type;
  _fd_z_type fd_z;




  typedef boost::shared_ptr< ::remote::basicResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::remote::basicResponse_<ContainerAllocator> const> ConstPtr;

}; // struct basicResponse_

typedef ::remote::basicResponse_<std::allocator<void> > basicResponse;

typedef boost::shared_ptr< ::remote::basicResponse > basicResponsePtr;
typedef boost::shared_ptr< ::remote::basicResponse const> basicResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::remote::basicResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::remote::basicResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace remote

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'remote': ['/home/sandy/sandy/ros/DronePi/DronePi_Remote/src/remote/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::remote::basicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::remote::basicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::remote::basicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::remote::basicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::remote::basicResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::remote::basicResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::remote::basicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6243dfb49d4798ec5507ff6c8927062a";
  }

  static const char* value(const ::remote::basicResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6243dfb49d4798ecULL;
  static const uint64_t static_value2 = 0x5507ff6c8927062aULL;
};

template<class ContainerAllocator>
struct DataType< ::remote::basicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "remote/basicResponse";
  }

  static const char* value(const ::remote::basicResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::remote::basicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 fb_x\n\
int32 fd_y\n\
int32 fd_z\n\
\n\
\n\
";
  }

  static const char* value(const ::remote::basicResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::remote::basicResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fb_x);
      stream.next(m.fd_y);
      stream.next(m.fd_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct basicResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::remote::basicResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::remote::basicResponse_<ContainerAllocator>& v)
  {
    s << indent << "fb_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fb_x);
    s << indent << "fd_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fd_y);
    s << indent << "fd_z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fd_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REMOTE_MESSAGE_BASICRESPONSE_H
